version: '3.8'

services:
  bicly:
    build:
      context: ./frontend
      args:
        - VITE_BROUTER_DIRECT_URL=/brouter
    volumes:
      - ./Privacy/privacy.md:/usr/share/nginx/html/privacy.md
      - ./Privacy/imprint.md:/usr/share/nginx/html/impressum.md
      - brouter_logs:/var/log/brouter
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - brouter
    restart: always

  brouter:
    image: ghcr.io/abrensch/brouter:latest
    volumes:
      - ./brouter/segments4:/segments4
      - brouter_logs:/var/log/brouter
    entrypoint: ["/bin/sh", "-c", "/brouter/server.sh 2>&1 | tee -a /var/log/brouter/brouter.log"]
    ports:
      - "17777:17777"
    restart: always

volumes:
  brouter_logs:
